version: 2
jobs:
  test-node-6:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - run: sudo apt-get install -y sox libatlas-base-dev
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-node6-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-node6-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node6-{{ checksum "package.json" }}
      - run: yarn test
  test-node-8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run: sudo apt-get install -y sox libatlas-base-dev
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-node8-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-node8-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node8-{{ checksum "package.json" }}
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install
      - run: npm publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-8
      - test-node-6
      - deploy:
          requires:
            - test-node-8
            - test-node-6
          filters:
            branches:
              only:
                - master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
